@baseUrl = https://fashionhub-backend-yuya.onrender.com
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5MTYzNGMyYy0wODdjLTRkOGMtYjBiYS04NDA4OTQ4MGI0OTciLCJ0aXBvX3VzdWFyaW8iOiJsb2ppc3RhIiwibG9qYV9pZCI6ImJiMGUxNDg3LWY2MGQtNGEzNS04MGU0LTZiOGU3YTE5ZWYxZSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc3MTM2Njk0OCwiZXhwIjoxNzcxOTcxNzQ4fQ.SeClhgnpGFoh9HIdhRt9_CEUCLPQemCklXW0X-Qq6R4

POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "nome": "Cliente de Teste",
  "email": "cliente3@teste.com",
  "senha": "senhalegalto1p",
  "tipo_usuario": "cliente",
  "telefone": "15999999999",
  "endereco": {
    "cep": "18000-000",
    "rua": "Rua dos Mafagafos",
    "numero": "1000",
    "bairro": "Centro",
    "cidade": "Sorocaba",
    "estado": "SP"
  }
}

###

POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "dev.danielmartins2@gmail.com",
  "senha": "senhalegalto1p"
}

###

GET {{baseUrl}}/api/transactions/debug-ids
Authorization: Bearer {{token}}

###

POST {{baseUrl}}/api/transactions/authorize
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "bag_id": 1
}

###

POST {{baseUrl}}/api/webhooks/payments
Content-Type: application/json

{
  "action": "payment.updated",
  "data": {
    "id": "ID_DO_PAGAMENTO_AQUI"
  }
}